return {
	-- Set the PDF viewer to be Skim and the compiler to lualatex
	src = "lervag/vimtex",
	lazy = false,
	config = function()
		-- Change which of these lines is commented based on os
		-- vim.g.vimtex_view_method = "zathura" -- Linux
		vim.g.vimtex_view_method = "skim" -- MacOS
		vim.g.vimtex_syntax_conceal_disable = 1
		vim.g.vimtex_indent_enabled = 0

		local latexmk_engine = {}
		latexmk_engine._ = '-lualatex --shell-escape'
		vim.g.vimtex_compiler_latexmk_engines = latexmk_engine
		vim.g.vimtex_mappings_enabled = 0
		vim.g.vimtex_imaps_enabled = 0
		vim.api.nvim_create_augroup('vimtex_config', { clear = true })
		vim.api.nvim_create_autocmd('FileType', {
			group = 'vimtex_config',
			pattern = 'tex',
			callback = function ()
				vim.keymap.set({'n'},						'<localleader>li',	'<plug>(vimtex-info)',													{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lI',	'<plug>(vimtex-info-full)',											{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lt',	'<plug>(vimtex-toc-open)',											{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lT',	'<plug>(vimtex-toc-toggle)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lq',	'<plug>(vimtex-log)',														{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lv',	'<plug>(vimtex-view)',													{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lr',	'<plug>(vimtex-reverse-search)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>ll',	'<plug>(vimtex-compile)',												{ buffer = 0 })
				vim.keymap.set({'n', 'x'},			'<localleader>lL',	'<plug>(vimtex-compile-selected)',							{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lS',	'<plug>(vimtex-compile-ss)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lk',	'<plug>(vimtex-stop)',													{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lK',	'<plug>(vimtex-stop-all)',											{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>le',	'<plug>(vimtex-errors)',												{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lo',	'<plug>(vimtex-compile-output)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lg',	'<plug>(vimtex-status)',												{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lG',	'<plug>(vimtex-status-all)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lc',	'<plug>(vimtex-clean)',													{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lC',	'<plug>(vimtex-clean-full)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lm',	'<plug>(vimtex-imaps-list)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lx',	'<plug>(vimtex-reload)',												{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>lX',	'<plug>(vimtex-reload-state)',									{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>ls',	'<plug>(vimtex-toggle-main)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<localleader>la',	'<plug>(vimtex-context-menu)',									{ buffer = 0 })
				vim.keymap.set({'n'},						'dse',							'<plug>(vimtex-env-delete)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'dsc',							'<plug>(vimtex-cmd-delete)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'ds$',							'<plug>(vimtex-env-delete-math)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'dsd',							'<plug>(vimtex-delim-delete)',									{ buffer = 0 })
				vim.keymap.set({'n'},						'cse',							'<plug>(vimtex-env-change)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'csc',							'<plug>(vimtex-cmd-change)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'cs$',							'<plug>(vimtex-env-change-math)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'csd',							'<plug>(vimtex-delim-change-math)',							{ buffer = 0 })
				vim.keymap.set({'n', 'x'},			'tsf',							'<plug>(vimtex-cmd-toggle-frac)',								{ buffer = 0 })
				-- vim.keymap.set({'n'},						'',									'<plug>(vimtex-cmd-toggle-star-agn)', 					{ buffer = 0 })
				vim.keymap.set({'n'},						'tsc',							'<plug>(vimtex-cmd-toggle-star)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'tss',							'<plug>(vimtex-env-toggle-star)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'tse',							'<plug>(vimtex-env-toggle)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'ts$',							'<plug>(vimtex-env-toggle-math)',								{ buffer = 0 })
				vim.keymap.set({'n'},						'tsb',							'<plug>(vimtex-env-toggle-break)',							{ buffer = 0 })
				vim.keymap.set({'n'},						'<F6>',							'<plug>(vimtex-env-surround-line)',							{ buffer = 0 })
				-- vim.keymap.set({'n'},						'',									'<plug>(vimtex-env-surround-operator)',					{ buffer = 0 })
				vim.keymap.set({'x'},						'<F6>',							'<plug>(vimtex-env-surround-visual)',						{ buffer = 0 })
				vim.keymap.set({'n', 'x'},			'tsd',							'<plug>(vimtex-delim-toggle-modifier)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x'},			'tsD',							'<plug>(vimtex-delim-toggle-modifier-reverse)',	{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'i'},	'<F7>',							'<plug>(vimtex-cmd-create)',										{ buffer = 0 })
				-- vim.keymap.set({'i'},						']]',								'<plug>(vimtex-delim-close)',										{ buffer = 0 })
				vim.keymap.set({'n'},						'<F8>',							'<plug>(vimtex-delim-add-modifiers)',						{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'ac',								'<plug>(vimtex-ac)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'ic',								'<plug>(vimtex-ic)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'ad',								'<plug>(vimtex-ad)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'id',								'<plug>(vimtex-id)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'ae',								'<plug>(vimtex-ae)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'ie',								'<plug>(vimtex-ie)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'a$',								'<plug>(vimtex-a$)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'i$',								'<plug>(vimtex-i$)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'aP',								'<plug>(vimtex-aP)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'iP',								'<plug>(vimtex-iP)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'am',								'<plug>(vimtex-am)',					{ buffer = 0 })
				vim.keymap.set({'x', 'o'},			'im',								'<plug>(vimtex-im)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'%',								'<plug>(vimtex-%)',						{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']]',								'<plug>(vimtex-]])',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'][',								'<plug>(vimtex-][)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[]',								'<plug>(vimtex-[])',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[[',								'<plug>(vimtex-[[)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']m',								'<plug>(vimtex-]m)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']M',								'<plug>(vimtex-]M)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[m',								'<plug>(vimtex-[m)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[M',								'<plug>(vimtex-[M)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']n',								'<plug>(vimtex-]n)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']N',								'<plug>(vimtex-]N)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[n',								'<plug>(vimtex-[n)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[N',								'<plug>(vimtex-[N)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']r',								'<plug>(vimtex-]r)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']R',								'<plug>(vimtex-]R)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[r',								'<plug>(vimtex-[r)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[R',								'<plug>(vimtex-[R)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']/',								'<plug>(vimtex-]/)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	']*',								'<plug>(vimtex-]star)',				{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[/',								'<plug>(vimtex-[/)',					{ buffer = 0 })
				vim.keymap.set({'n', 'x', 'o'},	'[*',								'<plug>(vimtex-[star)',				{ buffer = 0 })
				vim.keymap.set({'n'},						'K',								'<plug>(vimtex-doc-package)', { buffer = 0 })
			end,
		})
	end
}
